version: "3.8"
services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: lamoda
      POSTGRES_PASSWORD: lamoda
      POSTGRES_DB: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "3001:5432"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/lamoda
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - app
        - postgres
  app:
    build: ./app
    volumes:
      - ..:/var/www/lamoda
    ports:
      - "9000:9000"
    depends_on:
      - postgres
networks:
  lamoda_network:
    ipam:
      config:
        - subnet: '192.168.90.0/24'
volumes:
  postgres:
